name: moma_core
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0

  # https://pub.dev/packages/pretty_dio_logger/versions/1.2.0-beta
  pretty_dio_logger: ^1.2.0-beta-1

  # dio logging interceptor
  # https://pub.dev/packages/dio_logging_interceptor/install
  dio_logging_interceptor: ^1.0.1

  # Http custom interceptors
  # https://pub.dev/packages/http_interceptor
  http_interceptor: ^0.4.1

  drift: ^1.6.0

  rxdart: ^0.26.0

  intl: ^0.17.0

  # JWT Decoder
  # https://pub.dev/packages/jwt_decoder
  jwt_decoder: ^2.0.1

  # Also use the latest version.
  sqlite3_flutter_libs: ^0.5.0

  # Path Provider - Helper to find the database path on mobile
  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.10

  path_provider_windows: ^2.0.5

  flutter_svg: ^1.0.3

  path: ^1.8.0

  undo: ^1.4.0

  package_info_plus: ^1.3.0

  moor_db_viewer: ^5.0.0

  # Flutter Secure Storage
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^5.0.2

  shared_preferences: ^2.0.5

  drift_inspector: ^1.0.0

  equatable: ^2.0.3

  # Cool extensions dependencies
  # https://pub.dev/packages/dart_extensions
  dart_extensions: ^2.0.5

  # Wrapper fot http requests
  # https://pub.dev/packages/retrofit
  retrofit: ^3.0.0

  # https://pub.dev/packages/tuple/install
  tuple: ^2.0.0

  floor: ^1.2.0

  # Json Decoder/Encoder
  # https://pub.dev/packages/json_serializable/install
  json_serializable: ^5.0.1

dev_dependencies:
  build_runner: ^2.1.5
  retrofit_generator: any
  drift_dev: ^1.6.0
  build_web_compilers: ^3.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0

dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 6105be75a3d4b5c795b7648c8a90f724ea102cb7
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 6105be75a3d4b5c795b7648c8a90f724ea102cb7
      path: drift_dev
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 6105be75a3d4b5c795b7648c8a90f724ea102cb7
      path: sqlparser

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/jsons/
    - assets/translations/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
